### ISSUE TITLE
InstallError: Error: 'conda' can only be installed into the root environment

### ISSUE THREAD

**Issue by LisaSikkema** [LungCellAtlas/scRNAseq_pipelines#6]
issue from testrun Nick @mxposed @wathom 
I work on shared HPC cluster. We have conda 4.3.30 already available, and we cannot run commands as root. Conda environment setup didn't work. First problem with it was "InstallError: Error: 'conda' can only be installed into the root environment". Related to this command:  https://github.com/LungCellAtlas/scRNAseq_pipelines/blob/master/LCA_pipeline_setup.sh#L344

**Comment by LisaSikkema** [comment]
Hi Nick, I noticed a small mistake in the code that added an excess slash to the path prefix in the conda environment (see your log:
"Creating conda environment in .//cr3-velocyto-scanpy..."
)
This didn't create problems when I testran the script, but I fixed it now in case it helps.

Did you run the script from an activated conda environment? 
Based on some googling, it seems like this problem occurs if you cloned your conda root at any point. 
"If you clone root you get conda-build and conda-env in your new environment but afaik they shouldn't be there and are not required outside root provided root remains on your path. So if you remove them from your non-root env first your command should work
```
source activate my-env
conda remove conda-build
conda remove conda-env
conda update anaconda.
```
"
Is it possible that you have a cloned root?

**Comment by mxposed** [comment]
I haven't run the command with any activated conda environment, I believe. Unless the default one gives such a behaviour. Will try to create a new conda env manually and report

**Comment by LisaSikkema** [comment]
Ok! Any updates?

**Comment by mxposed** [comment]
Well, surprisingly, the error message was exactly correct: if I remove `conda=4.8.2=py36_0` requirement from the command on line 344, the environment gets created.
I wonder if this error is a feature of a multi-user conda installation, or just different conda version, but do you really need that conda package installed in your custom environment?

**Comment by mxposed** [comment]
Next problem is with activating the environment: https://github.com/LungCellAtlas/scRNAseq_pipelines/blob/master/LCA_pipeline_setup.sh#L354

My version of conda does not have the option `--base`, instead `--root`, but also does not have `etc/profile.d/conda.sh` file, and if I get it right, expects people to activate environment with `source activate` and not `conda activate`

**Comment by LisaSikkema** [comment]
okay great we're making progress! Will ask Thomas @wathom  (who worked on the conda environment setup) if he thinks it's okay to remove the conda requirement from line 344. 
I'll now try to adapt the script so that it uses different environment activations depending on the conda version.

**Comment by LisaSikkema** [comment]
okay I added accounting for conda versions in the LCA_pipeline_setup.sh file (it requires the versiontester.sh script that can now be found under /src). For now, I replaced the `source [path/to/conda.sh]` with nothing for conda versions below 4.6, it seems like it wasn't necessary to do anything similar before this version, but I'm not sure. Could you see if the new code prevents your errors?
I haven't removed the `conda=4.8.2=py36_0` argument from the conda create command, waiting for Thomas's input on this.

**Comment by LuckyMD** [comment]
@mxposed it looks like you're still running a pretty old `conda` version ;). Might be time to update past version 4.4 :D. I think `source activate` was what I used about 2 years ago ;).

**Comment by mxposed** [comment]
Thank you, Lisa, I'll try that later.

@LuckyMD you're right, but this is what we have on a HPC cluster where I work (mostly). I'll ask the admins if they can update it

**Comment by LuckyMD** [comment]
you can't just update via `conda update conda` yourself? That's some harsh restrictions ^^.

**Comment by mxposed** [comment]
Hi. Ok, sorry, I found a newer conda and all the environment stuff went well.

Next problem is with building the genome: `ERROR: Checksum 11885 860561 Homo_sapiens.GRCh38.dna.primary_assembly.fa.gz not found in CHECKSUMS_FASTA file, exit.`

However:
```
$ fgrep Homo_sapiens.GRCh38.dna.primary_assembly.fa.gz ../pipeline-files/refgenomes/CHECKSUMS_FASTA
11885 860561    Homo_sapiens.GRCh38.dna.primary_assembly.fa.gz
```

**Comment by LisaSikkema** [comment]
Ok! I'll close this issue and open a new one about the checksum. 
So in the end you never tested my added code with the older conda version right? (Asking just so I have documented whether it was tested or not).

**Comment by mxposed** [comment]
Yes, you're right, I haven't tested your new code with the older version. Sorry about that. Do you want me to?

**Comment by LisaSikkema** [comment]
No I think it's okay, I don't expect people to still be using conda versions that old. If they do, they can test it then
