### ISSUE TITLE
checksum "not found" while sum is correct

### ISSUE THREAD

**Issue by LisaSikkema** [LungCellAtlas/scRNAseq_pipelines#7]
issue with testrun @mxposed: 
Next problem is with building the genome: ERROR: Checksum 11885 860561 Homo_sapiens.GRCh38.dna.primary_assembly.fa.gz not found in CHECKSUMS_FASTA file, exit.

However:

`$ fgrep Homo_sapiens.GRCh38.dna.primary_assembly.fa.gz ../pipeline-files/refgenomes/CHECKSUMS_FASTA
11885 860561    Homo_sapiens.GRCh38.dna.primary_assembly.fa.gz`

**Comment by LisaSikkema** [comment]
that's strange. Could you go to the folder with the CHECKSUMS_FASTA and your genome.fa.gz file (do you have them in the same directory?) and run:
```
sum_fa=`sum "genome.fa.gz"`  
valfa=`grep "$sum_fa Homo_sapiens.GRCh38.dna.primary_assembly.fa.gz" CHECKSUMS_FASTA | wc -l`  
echo $valfa
```

does it print 1?

**Comment by mxposed** [comment]
It prints 0. The problem is in the whitespace: in my CHECKSUMS_FASTA there's a tab after the sum, not a space.

`valfa=`grep -P "$sum_fa\tHomo_sapiens.GRCh38.dna.primary_assembly.fa.gz" CHECKSUMS_FASTA | wc -l``

This works, but it's maybe not as portable

**Comment by LisaSikkema** [comment]
okay the script now also includes a check for [checksum][tab][filename] (I used $(printf '\t') for the tab sign), and then checks if either a line with space or a line with tab is in there. Could you pull the new code and see if it's fixed now?

**Comment by LisaSikkema** [comment]
hi @mxposed , have you had time to try the updated code yet?

**Comment by mxposed** [comment]
Hi, I'm sorry for a long response, we had a dense couple of weeks.
Yes, thank you, the updated code helps, it goes past the checksum phase.
I still haven't gotten to the end of `setup` script, but hopefully soon, will keep you updated

**Comment by LisaSikkema** [comment]
ok thanks a lot!
